apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: nepetrov7/paymentservice:v0.0.2
        resources: {}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0%
