apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nepetrov7/nginx-otus
      volumeMounts:
        - name: app
          mountPath: /app
      # readinessProbe:
      #   httpGet:
      #     path: /index.html
      #     port: 80
      livenessProbe:
        tcpSocket: { port: 8000 }
  initContainers:
    - name: init-myservice
      image: busybox:1.31.0
      command:  ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
